\c uacl_db;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(56) NOT NULL,
    email VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	encoded_id VARCHAR(128) UNIQUE NOT NULL
);

ALTER TABLE users ADD CONSTRAINT email_unqiue UNIQUE (email)