version: '3'

services:
  api:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro