version: '3'

services:
  test_db:
    image: ghcr.io/tombowyerresearchproject/postgres_db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: tom123
      POSTGRES_USER: tom
    restart: unless-stopped