version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/uacl_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uacl.rule=Host(`uacl.emotives.net`)"
      - "traefik.http.routers.uacl.tls=true"
      - "traefik.http.routers.uacl.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    logging:
      driver: syslog
    environment:
      DATABASE_URL: postgres://tom:tom123@postgres_db:5432/uacl_db
      HOST: 0.0.0.0
      PORT: 80
      PRIVATE_KEY: /jwt/private.key
      PUBLIC_KEY: /jwt/public.key
      SECRET: qutCreate
      CHATTER_URL: http://chatter/user
      CHATTER_SECRET: chatterSecret
      AUTOLOGIN_URL: https://www.emotives.net/login?token=
      AUTOLOGIN_CREATE_USERS: imtom,
      EMAIL_FROM: emotives.acc@gmail.com
      EMAIL_PASSWORD: "${GMAIL_PASSWORD:-}"
      EMAIL_LEVEL: PROD
      ALLOWED_ORIGINS: https://emotives.net,https://wwww.emotives.net
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - uacl

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik