version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/uacl/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uacl.rule=Host(`uacl.localhost`)"
      - "traefik.http.routers.uacl.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://tom:tom123@postgres_db:5432/uacl_db
      HOST: 0.0.0.0
      PORT: 80
      PRIVATE_KEY: /app/jwt/private.key
      PUBLIC_KEY: /app/jwt/public.key
      SECRET: qutCreate
      AUTOLOGIN_URL: http://localhost/login?token=
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - uacl

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
