version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/uacl/Dockerfile.prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      - BASE_HOST=http://
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uacl.rule=Host(`uacl.emotives.net`)"
      - "traefik.http.routers.uacl.tls=true"
      - "traefik.http.routers.uacl.tls.certresolver=letsencrypt"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - uacl
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tom123
      POSTGRES_USER: tom
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ../../database/Initial/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      default:

volumes:
  postgres-data:

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik