FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN go mod download

RUN go build ./cmd/api

FROM scratch

COPY --from=builder /app/api /app/api
COPY --from=builder /app/jwt/ /app/jwt/

EXPOSE 80

CMD ["/app/api"]