version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/uacl_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uacl.rule=Host(`uacl.emotives.net`)"
      - "traefik.http.routers.uacl.tls=true"
      - "traefik.http.routers.uacl.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://tom:tom123@db:5432/uacl_db
      HOST: 0.0.0.0
      PORT: 80
      PRIVATE_KEY: /jwt/private.key
      PUBLIC_KEY: /jwt/public.key
      SECRET: qutCreate
    depends_on:
      - "db"
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - uacl
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tom123
      POSTGRES_USER: tom
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ../../database/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      default:

volumes:
  postgres-data:

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik