# NOTE: if you want to use github as opposed to my self hosted option for running test
# add a os in the matrix such as os: [ubuntu-latest] and then change runs-on to ${{ matrix.os }}
on: [push, pull_request]
name: Test
jobs:
  full_run:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: self-hosted
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39
    - name: Test
      run: go test -v ./..