# Build docker images and ssh onto machine and deploy
name: Merge PR
on:
  pull_request:
    types: [closed]
jobs:
  build-images:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        run: echo yo
  update-images:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        run: echo yo