name: Merged items

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-push-image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Build image
        run: ./scripts/build.sh
      - name: Log in and push
        run: |
          echo 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 | docker login ghcr.io -u imthetom --password-stdin
          docker push ghcr.io/tombowyerresearchproject/uacl_api:latest
